name: Node.js CI

on:
  push:
    branches: [ "main" ]           # Trigger on push to the main branch
  pull_request:
    branches: [ "main" ]           # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest         # GitHub-hosted Ubuntu VM

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.9.1
      with:
        node-version: '18'        # Set your Node.js version here
                                  #

    - name: Install dependencies
      run: npm install
          
